// Reference data for lab metrics tracked by the app.
// Ranges are general adult educational reference values, NOT medical advice.
export type NutrientCategory =
  | "Protein & Nutrition Status"
  | "Blood Sugar"
  | "Lipids"
  | "Vitamins"
  | "Minerals & Electrolytes"
  | "Iron Panel"
  | "Trace Elements";

export interface NutrientDef {
  key: string;
  name: string;
  unit: string;
  low: number;
  high: number;
  min: number;
  max: number;
  category: NutrientCategory;
  description: string;
  lowMeaning: string;
  highMeaning: string;
  dietaryFactors: string;
  lifestyleTips: string[];
}

// Sorted alphabetically by name.
export const NUTRIENTS: NutrientDef[] = [
  {
    key: "vitamin-d-25oh",
    name: "25-Hydroxyvitamin D",
    unit: "ng/mL",
    low: 30,
    high: 100,
    min: 0,
    max: 150,
    category: "Vitamins",
    description: "The main storage form of vitamin D in the blood; reflects sun exposure, diet, and supplementation.",
    lowMeaning: "Low vitamin D is linked to weaker bones, poor calcium absorption, low mood, and reduced immune function.",
    highMeaning: "Very high levels are usually caused by over-supplementation and can raise blood calcium to unsafe levels.",
    dietaryFactors: "Fatty fish, egg yolks, fortified milk/cereal, mushrooms, and sensible sun exposure.",
    lifestyleTips: [
      "Get 10-20 minutes of midday sunlight several times a week",
      "Add fatty fish (salmon, mackerel) twice a week",
      "Consider a vitamin D3 supplement with a doctor's guidance",
    ],
  },
  {
    key: "albumin",
    name: "Albumin",
    unit: "g/dL",
    low: 3.5,
    high: 5.0,
    min: 1,
    max: 6,
    category: "Protein & Nutrition Status",
    description: "The most abundant blood protein; a marker of overall protein status, liver, and kidney function.",
    lowMeaning: "Low albumin can indicate poor protein intake, liver disease, kidney loss, or chronic inflammation.",
    highMeaning: "High albumin is uncommon and often reflects dehydration.",
    dietaryFactors: "Lean meats, eggs, dairy, beans, and adequate overall calorie/protein intake.",
    lifestyleTips: [
      "Add a lean protein source to every meal",
      "Stay consistently hydrated through the day",
      "Track daily protein intake for a week",
    ],
  },
  {
    key: "ceruloplasmin",
    name: "Ceruloplasmin",
    unit: "mg/dL",
    low: 20,
    high: 60,
    min: 0,
    max: 100,
    category: "Trace Elements",
    description: "A copper-transport protein made by the liver; used to assess copper status and liver health.",
    lowMeaning: "Low levels can reflect copper deficiency or certain genetic/liver conditions.",
    highMeaning: "High levels can occur with inflammation, pregnancy, or excess copper intake.",
    dietaryFactors: "Shellfish, nuts, seeds, whole grains, and organ meats supply dietary copper.",
    lifestyleTips: [
      "Add copper-rich foods like cashews and lentils weekly",
      "Avoid excess zinc supplementation, which blocks copper absorption",
    ],
  },
  {
    key: "chloride",
    name: "Chloride",
    unit: "mmol/L",
    low: 96,
    high: 106,
    min: 80,
    max: 120,
    category: "Minerals & Electrolytes",
    description: "An electrolyte that works with sodium to maintain fluid balance and blood pH.",
    lowMeaning: "Low chloride is often linked to vomiting, dehydration, or excessive sweating.",
    highMeaning: "High chloride can be caused by dehydration or excess salt intake.",
    dietaryFactors: "Table salt, processed foods, seaweed, tomatoes, and olives.",
    lifestyleTips: [
      "Track fluid intake to stay well hydrated",
      "Moderate processed and heavily salted foods",
    ],
  },
  {
    key: "chromium",
    name: "Chromium",
    unit: "mcg/L",
    low: 0.1,
    high: 2.1,
    min: 0,
    max: 5,
    category: "Trace Elements",
    description: "A trace mineral that helps insulin regulate blood sugar.",
    lowMeaning: "Low chromium may contribute to impaired glucose tolerance.",
    highMeaning: "High levels are rare and usually linked to occupational exposure or supplementation.",
    dietaryFactors: "Broccoli, whole grains, green beans, nuts, and brewer's yeast.",
    lifestyleTips: [
      "Add broccoli or whole grains to meals a few times a week",
      "Limit refined sugar, which increases chromium excretion",
    ],
  },
  {
    key: "copper",
    name: "Copper",
    unit: "mcg/dL",
    low: 70,
    high: 140,
    min: 0,
    max: 200,
    category: "Trace Elements",
    description: "A trace mineral needed for iron metabolism, connective tissue, and nerve health.",
    lowMeaning: "Low copper can cause anemia, low white blood cell counts, and bone issues.",
    highMeaning: "High copper can be toxic and cause liver damage, nausea, or abdominal pain.",
    dietaryFactors: "Shellfish, organ meats, nuts, seeds, whole grains, and dark chocolate.",
    lifestyleTips: [
      "Add a small serving of nuts or seeds most days",
      "Avoid cooking acidic food in unlined copper cookware",
    ],
  },
  {
    key: "fasting-glucose",
    name: "Fasting Glucose",
    unit: "mg/dL",
    low: 70,
    high: 99,
    min: 40,
    max: 300,
    category: "Blood Sugar",
    description: "Blood sugar measured after at least 8 hours without food; a core screening test for diabetes risk.",
    lowMeaning: "Low fasting glucose (hypoglycemia) can cause shakiness, dizziness, and confusion.",
    highMeaning: "High fasting glucose suggests prediabetes or diabetes and insulin resistance.",
    dietaryFactors: "Refined carbohydrates, added sugar, portion sizes, fiber intake, and meal timing.",
    lifestyleTips: [
      "Take a 10-15 minute walk after meals",
      "Swap refined carbs for high-fiber whole grains",
      "Aim for 150 minutes of moderate exercise weekly",
    ],
  },
  {
    key: "ferritin",
    name: "Ferritin",
    unit: "ng/mL",
    low: 20,
    high: 250,
    min: 0,
    max: 500,
    category: "Iron Panel",
    description: "The body's main iron-storage protein; reflects total iron reserves.",
    lowMeaning: "Low ferritin usually means depleted iron stores and can precede iron-deficiency anemia.",
    highMeaning: "High ferritin can reflect iron overload, inflammation, liver disease, or infection.",
    dietaryFactors: "Red meat, poultry, seafood, beans, spinach, and vitamin C (boosts absorption).",
    lifestyleTips: [
      "Pair iron-rich foods with a vitamin C source",
      "Avoid coffee or tea directly with iron-rich meals",
    ],
  },
  {
    key: "folate",
    name: "Folate",
    unit: "ng/mL",
    low: 2.7,
    high: 17.0,
    min: 0,
    max: 25,
    category: "Vitamins",
    description: "Vitamin B9; essential for DNA synthesis, red blood cell production, and fetal development.",
    lowMeaning: "Low folate can cause fatigue, megaloblastic anemia, and in pregnancy raises birth-defect risk.",
    highMeaning: "High folate is usually from supplementation and can mask a B12 deficiency.",
    dietaryFactors: "Leafy greens, legumes, citrus fruit, and fortified grains.",
    lifestyleTips: [
      "Add a serving of leafy greens most days",
      "Include beans or lentils a few times a week",
    ],
  },
  {
    key: "hba1c",
    name: "HbA1c",
    unit: "%",
    low: 4.0,
    high: 5.6,
    min: 3,
    max: 14,
    category: "Blood Sugar",
    description: "Reflects average blood sugar over the past 2-3 months by measuring glucose bound to hemoglobin.",
    lowMeaning: "Very low HbA1c can reflect frequent low blood sugar episodes or certain blood disorders.",
    highMeaning: "High HbA1c (5.7-6.4% prediabetes, 6.5%+ diabetes range) indicates elevated average blood sugar.",
    dietaryFactors: "Overall carbohydrate quality/quantity, added sugar, fiber, and consistent meal patterns.",
    lifestyleTips: [
      "Build meals around vegetables, protein, and fiber first",
      "Add strength training twice a week to improve insulin sensitivity",
      "Set a goal to walk daily for 20-30 minutes",
    ],
  },
  {
    key: "hdl-cholesterol",
    name: "HDL Cholesterol",
    unit: "mg/dL",
    low: 40,
    high: 60,
    min: 0,
    max: 120,
    category: "Lipids",
    description: "\"Good\" cholesterol that helps clear excess cholesterol from the bloodstream.",
    lowMeaning: "Low HDL is linked to higher cardiovascular risk.",
    highMeaning: "High HDL is generally protective, not concerning, though very high levels can occasionally reflect a genetic pattern worth discussing with a doctor.",
    dietaryFactors: "Healthy fats (olive oil, nuts, fatty fish), fiber, and regular aerobic exercise.",
    lifestyleTips: [
      "Add olive oil or nuts as your primary fat source",
      "Do 30 minutes of aerobic exercise most days",
      "Quit smoking, which lowers HDL",
    ],
  },
  {
    key: "hemoglobin",
    name: "Hemoglobin",
    unit: "g/dL",
    low: 12.0,
    high: 16.5,
    min: 5,
    max: 20,
    category: "Iron Panel",
    description: "The oxygen-carrying protein in red blood cells (normal ranges vary somewhat by sex).",
    lowMeaning: "Low hemoglobin (anemia) causes fatigue, shortness of breath, and paleness.",
    highMeaning: "High hemoglobin can result from dehydration, smoking, or living at high altitude.",
    dietaryFactors: "Iron, vitamin B12, folate, and adequate hydration.",
    lifestyleTips: [
      "Add iron-rich foods paired with vitamin C",
      "Get screened for underlying causes if persistently low",
    ],
  },
  {
    key: "ionized-calcium",
    name: "Ionized Calcium",
    unit: "mg/dL",
    low: 4.6,
    high: 5.3,
    min: 3,
    max: 7,
    category: "Minerals & Electrolytes",
    description: "The biologically active, unbound form of calcium in the blood.",
    lowMeaning: "Low ionized calcium can cause muscle cramps, tingling, and in severe cases seizures.",
    highMeaning: "High ionized calcium can cause fatigue, kidney stones, and bone loss.",
    dietaryFactors: "Dairy, fortified plant milk, leafy greens, and vitamin D status.",
    lifestyleTips: [
      "Add a calcium source (dairy or fortified alternative) daily",
      "Pair calcium intake with adequate vitamin D",
    ],
  },
  {
    key: "ldl-cholesterol",
    name: "LDL Cholesterol",
    unit: "mg/dL",
    low: 0,
    high: 99,
    min: 0,
    max: 250,
    category: "Lipids",
    description: "\"Bad\" cholesterol that can build up in artery walls and raise heart disease risk.",
    lowMeaning: "Low LDL is generally favorable and not a health concern.",
    highMeaning: "High LDL raises the risk of atherosclerosis, heart attack, and stroke.",
    dietaryFactors: "Saturated/trans fat, dietary cholesterol, fiber intake, and body weight.",
    lifestyleTips: [
      "Replace saturated fats with unsaturated fats (olive oil, avocado)",
      "Add soluble fiber like oats and beans daily",
      "Aim for 150 minutes of moderate exercise weekly",
    ],
  },
  {
    key: "manganese",
    name: "Manganese",
    unit: "mcg/L",
    low: 4.0,
    high: 15.0,
    min: 0,
    max: 25,
    category: "Trace Elements",
    description: "A trace mineral involved in bone formation, metabolism, and antioxidant defense.",
    lowMeaning: "Low manganese is rare but may affect bone and connective tissue health.",
    highMeaning: "High manganese can be neurotoxic, usually from environmental/occupational exposure or liver disease.",
    dietaryFactors: "Whole grains, nuts, leafy greens, and tea.",
    lifestyleTips: [
      "Include whole grains or nuts regularly",
      "Discuss supplement use with a doctor if levels run high",
    ],
  },
  {
    key: "phosphorus",
    name: "Phosphorus",
    unit: "mg/dL",
    low: 2.5,
    high: 4.5,
    min: 1,
    max: 7,
    category: "Minerals & Electrolytes",
    description: "A mineral vital for bone structure, energy storage (ATP), and cell membranes.",
    lowMeaning: "Low phosphorus can cause muscle weakness, bone pain, and fatigue.",
    highMeaning: "High phosphorus is often linked to kidney function and can weaken bones over time.",
    dietaryFactors: "Dairy, meat, fish, nuts, and processed foods with phosphate additives.",
    lifestyleTips: [
      "Choose whole foods over heavily processed foods",
      "Balance dairy and protein intake across the day",
    ],
  },
  {
    key: "potassium",
    name: "Potassium",
    unit: "mmol/L",
    low: 3.5,
    high: 5.0,
    min: 2,
    max: 7,
    category: "Minerals & Electrolytes",
    description: "An electrolyte critical for heart rhythm, muscle contraction, and nerve signaling.",
    lowMeaning: "Low potassium can cause muscle cramps, weakness, and irregular heartbeat.",
    highMeaning: "High potassium can be dangerous and cause serious heart rhythm problems.",
    dietaryFactors: "Bananas, potatoes, leafy greens, beans, and oranges.",
    lifestyleTips: [
      "Add a potassium-rich fruit or vegetable daily",
      "Stay hydrated and avoid excessive salt substitutes without guidance",
    ],
  },
  {
    key: "prealbumin",
    name: "Prealbumin",
    unit: "mg/dL",
    low: 15,
    high: 36,
    min: 0,
    max: 50,
    category: "Protein & Nutrition Status",
    description: "A short half-life protein used to detect recent changes in nutritional status.",
    lowMeaning: "Low prealbumin suggests recent poor protein/calorie intake or acute inflammation.",
    highMeaning: "High prealbumin is uncommon and typically not clinically significant on its own.",
    dietaryFactors: "Adequate total protein and calorie intake.",
    lifestyleTips: [
      "Add a protein source to every meal and snack",
      "Track intake if recovering from illness or reduced appetite",
    ],
  },
  {
    key: "protein-total",
    name: "Protein",
    unit: "g/dL",
    low: 6.0,
    high: 8.3,
    min: 3,
    max: 10,
    category: "Protein & Nutrition Status",
    description: "Total blood protein, mainly albumin and globulins; a broad marker of nutrition, liver, and immune status.",
    lowMeaning: "Low total protein can indicate malnutrition, liver or kidney disease, or malabsorption.",
    highMeaning: "High total protein can reflect dehydration or chronic inflammation/infection.",
    dietaryFactors: "Lean meats, fish, eggs, dairy, legumes, and overall diet quality.",
    lifestyleTips: [
      "Aim for a protein source at each meal",
      "Stay well hydrated to avoid false readings",
    ],
  },
  {
    key: "rbc-magnesium",
    name: "RBC Magnesium",
    unit: "mg/dL",
    low: 4.2,
    high: 6.8,
    min: 0,
    max: 10,
    category: "Minerals & Electrolytes",
    description: "Measures magnesium stored inside red blood cells, a more accurate long-term status marker than serum magnesium.",
    lowMeaning: "Low RBC magnesium can cause muscle cramps, fatigue, and irregular heartbeat.",
    highMeaning: "High levels are uncommon and usually linked to kidney dysfunction or supplementation.",
    dietaryFactors: "Leafy greens, nuts, seeds, whole grains, and dark chocolate.",
    lifestyleTips: [
      "Add a handful of nuts or seeds most days",
      "Include leafy greens at dinner several times a week",
    ],
  },
  {
    key: "selenium",
    name: "Selenium",
    unit: "mcg/L",
    low: 70,
    high: 150,
    min: 0,
    max: 250,
    category: "Trace Elements",
    description: "A trace mineral and antioxidant important for thyroid function and immune defense.",
    lowMeaning: "Low selenium may impair thyroid function and immune response.",
    highMeaning: "High selenium (selenosis) can cause hair loss, nail brittleness, and nerve damage.",
    dietaryFactors: "Brazil nuts, seafood, eggs, and sunflower seeds.",
    lifestyleTips: [
      "One or two Brazil nuts a day can meet most needs",
      "Avoid stacking multiple selenium supplements",
    ],
  },
  {
    key: "serum-calcium",
    name: "Serum Calcium",
    unit: "mg/dL",
    low: 8.5,
    high: 10.2,
    min: 5,
    max: 13,
    category: "Minerals & Electrolytes",
    description: "Total calcium in the blood, essential for bones, muscle function, and nerve signaling.",
    lowMeaning: "Low serum calcium can cause muscle cramps, numbness, and tingling.",
    highMeaning: "High serum calcium can cause fatigue, kidney stones, and digestive issues.",
    dietaryFactors: "Dairy, fortified foods, leafy greens, and vitamin D status.",
    lifestyleTips: [
      "Add a calcium-rich food daily",
      "Get regular weight-bearing exercise for bone health",
    ],
  },
  {
    key: "serum-iron",
    name: "Serum Iron",
    unit: "mcg/dL",
    low: 60,
    high: 170,
    min: 0,
    max: 250,
    category: "Iron Panel",
    description: "The amount of iron currently circulating in the bloodstream, bound to transferrin.",
    lowMeaning: "Low serum iron can cause fatigue, weakness, and pale skin.",
    highMeaning: "High serum iron may indicate excess supplementation or iron overload conditions.",
    dietaryFactors: "Red meat, poultry, seafood, beans, and vitamin C for absorption.",
    lifestyleTips: [
      "Pair iron-rich meals with vitamin C-rich foods",
      "Avoid unnecessary iron supplements without testing",
    ],
  },
  {
    key: "serum-magnesium",
    name: "Serum Magnesium",
    unit: "mg/dL",
    low: 1.7,
    high: 2.2,
    min: 0,
    max: 4,
    category: "Minerals & Electrolytes",
    description: "Reflects magnesium circulating in the blood; involved in muscle, nerve, and heart function.",
    lowMeaning: "Low serum magnesium can cause cramps, fatigue, and irregular heart rhythm.",
    highMeaning: "High serum magnesium is often related to kidney function or supplement overuse.",
    dietaryFactors: "Nuts, seeds, whole grains, leafy greens, and legumes.",
    lifestyleTips: [
      "Add magnesium-rich foods like almonds and spinach",
      "Limit alcohol, which depletes magnesium",
    ],
  },
  {
    key: "sodium",
    name: "Sodium",
    unit: "mmol/L",
    low: 135,
    high: 145,
    min: 110,
    max: 170,
    category: "Minerals & Electrolytes",
    description: "The primary electrolyte regulating fluid balance and blood pressure.",
    lowMeaning: "Low sodium can cause confusion, headache, nausea, and in severe cases seizures.",
    highMeaning: "High sodium usually reflects dehydration or excess salt intake.",
    dietaryFactors: "Table salt, processed and restaurant foods, and fluid intake.",
    lifestyleTips: [
      "Track fluid intake, especially in hot weather or with exercise",
      "Read labels to reduce added sodium in processed foods",
    ],
  },
  {
    key: "tibc",
    name: "TIBC",
    unit: "mcg/dL",
    low: 250,
    high: 450,
    min: 100,
    max: 600,
    category: "Iron Panel",
    description: "Total Iron Binding Capacity — measures the blood's capacity to carry iron on transferrin.",
    lowMeaning: "Low TIBC can be seen with inflammation, liver disease, or iron overload.",
    highMeaning: "High TIBC usually indicates iron deficiency, as the body produces more transferrin to compensate.",
    dietaryFactors: "Iron intake and absorption, protein status, and inflammation.",
    lifestyleTips: [
      "Increase iron-rich foods if TIBC is high with low ferritin",
      "Recheck the full iron panel together for context",
    ],
  },
  {
    key: "total-cholesterol",
    name: "Total Cholesterol",
    unit: "mg/dL",
    low: 125,
    high: 200,
    min: 50,
    max: 350,
    category: "Lipids",
    description: "The sum of HDL, LDL, and a portion of triglycerides; a general cardiovascular risk screen.",
    lowMeaning: "Very low total cholesterol is uncommon and can relate to malnutrition, liver disease, or hyperthyroidism.",
    highMeaning: "High total cholesterol raises long-term cardiovascular risk, especially if LDL is elevated.",
    dietaryFactors: "Saturated fat, dietary cholesterol, fiber, and overall dietary pattern.",
    lifestyleTips: [
      "Shift toward a Mediterranean-style eating pattern",
      "Add 150 minutes of moderate exercise weekly",
      "Increase soluble fiber (oats, beans, fruit)",
    ],
  },
  {
    key: "transferrin",
    name: "Transferrin",
    unit: "mg/dL",
    low: 200,
    high: 360,
    min: 100,
    max: 500,
    category: "Iron Panel",
    description: "The main protein that transports iron through the blood.",
    lowMeaning: "Low transferrin can be seen with inflammation, liver disease, or malnutrition.",
    highMeaning: "High transferrin usually reflects iron deficiency.",
    dietaryFactors: "Iron and protein intake, plus overall liver health.",
    lifestyleTips: [
      "Combine with ferritin and serum iron for a full picture",
      "Add iron-rich, protein-rich foods if levels run high with low iron",
    ],
  },
  {
    key: "triglycerides",
    name: "Triglycerides",
    unit: "mg/dL",
    low: 0,
    high: 149,
    min: 0,
    max: 500,
    category: "Lipids",
    description: "A type of fat in the blood used for energy; strongly influenced by diet and body weight.",
    lowMeaning: "Low triglycerides are generally not a health concern.",
    highMeaning: "High triglycerides raise cardiovascular and pancreatitis risk, and often relate to sugar/alcohol intake.",
    dietaryFactors: "Added sugar, refined carbs, alcohol, and excess calorie intake.",
    lifestyleTips: [
      "Cut back on added sugar and sugary drinks",
      "Limit alcohol intake",
      "Add 30 minutes of cardio most days",
    ],
  },
  {
    key: "vitamin-a",
    name: "Vitamin A",
    unit: "mcg/dL",
    low: 20,
    high: 80,
    min: 0,
    max: 120,
    category: "Vitamins",
    description: "A fat-soluble vitamin essential for vision, immune function, and skin health.",
    lowMeaning: "Low vitamin A can cause night blindness and increased infection risk.",
    highMeaning: "High vitamin A (usually from supplements) can be toxic, causing headaches and liver damage.",
    dietaryFactors: "Liver, eggs, dairy, and orange/yellow vegetables (carrots, sweet potatoes).",
    lifestyleTips: [
      "Add orange and leafy green vegetables a few times a week",
      "Avoid stacking multiple vitamin A supplements",
    ],
  },
  {
    key: "vitamin-b1",
    name: "Vitamin B1",
    unit: "nmol/L",
    low: 70,
    high: 180,
    min: 0,
    max: 300,
    category: "Vitamins",
    description: "Thiamine; needed to convert food into energy and support nerve function.",
    lowMeaning: "Low B1 can cause fatigue, irritability, and in severe cases nerve or heart problems.",
    highMeaning: "High levels are rare since excess B1 is typically excreted in urine.",
    dietaryFactors: "Whole grains, pork, legumes, nuts, and seeds.",
    lifestyleTips: [
      "Choose whole grains over refined grains",
      "Limit alcohol, which impairs B1 absorption",
    ],
  },
  {
    key: "vitamin-b12",
    name: "Vitamin B12",
    unit: "pg/mL",
    low: 200,
    high: 900,
    min: 0,
    max: 1500,
    category: "Vitamins",
    description: "Essential for red blood cell formation and nerve health; mainly found in animal foods.",
    lowMeaning: "Low B12 can cause fatigue, numbness/tingling, memory issues, and anemia.",
    highMeaning: "High B12 is usually from supplementation, though persistently high levels warrant a doctor's review.",
    dietaryFactors: "Meat, fish, eggs, dairy, and fortified foods (important for vegans/vegetarians).",
    lifestyleTips: [
      "Add a B12 source daily if eating a plant-based diet",
      "Consider a B12 supplement if levels run low",
    ],
  },
  {
    key: "vitamin-b6",
    name: "Vitamin B6",
    unit: "ng/mL",
    low: 5,
    high: 50,
    min: 0,
    max: 100,
    category: "Vitamins",
    description: "Supports protein metabolism, red blood cell production, and brain development.",
    lowMeaning: "Low B6 can cause irritability, confusion, and skin problems.",
    highMeaning: "High B6, usually from supplements, can cause nerve damage over time.",
    dietaryFactors: "Poultry, fish, potatoes, chickpeas, and fortified cereals.",
    lifestyleTips: [
      "Add chickpeas, poultry, or fish weekly",
      "Avoid high-dose B6 supplements without guidance",
    ],
  },
  {
    key: "vitamin-c",
    name: "Vitamin C",
    unit: "mg/dL",
    low: 0.4,
    high: 2.0,
    min: 0,
    max: 3,
    category: "Vitamins",
    description: "An antioxidant vitamin needed for collagen synthesis, immune function, and iron absorption.",
    lowMeaning: "Low vitamin C can cause fatigue, bruising, gum problems, and slow wound healing.",
    highMeaning: "High vitamin C is usually harmless and excreted, though very high doses can cause GI upset.",
    dietaryFactors: "Citrus fruit, berries, bell peppers, and broccoli.",
    lifestyleTips: [
      "Add a citrus fruit or bell pepper daily",
      "Pair vitamin C foods with iron-rich meals",
    ],
  },
  {
    key: "vitamin-e",
    name: "Vitamin E",
    unit: "mg/L",
    low: 5.5,
    high: 17.0,
    min: 0,
    max: 25,
    category: "Vitamins",
    description: "A fat-soluble antioxidant that protects cell membranes from oxidative damage.",
    lowMeaning: "Low vitamin E can impair immune function and, rarely, nerve health.",
    highMeaning: "High vitamin E (usually from supplements) can interfere with blood clotting.",
    dietaryFactors: "Nuts, seeds, vegetable oils, and leafy greens.",
    lifestyleTips: [
      "Add a small handful of nuts or seeds daily",
      "Use olive or sunflower oil as a primary cooking fat",
    ],
  },
  {
    key: "zinc",
    name: "Zinc",
    unit: "mcg/dL",
    low: 60,
    high: 120,
    min: 0,
    max: 200,
    category: "Minerals & Electrolytes",
    description: "A trace mineral vital for immune function, wound healing, and taste/smell.",
    lowMeaning: "Low zinc can cause slow wound healing, hair loss, and frequent infections.",
    highMeaning: "High zinc, often from supplements, can interfere with copper absorption and cause nausea.",
    dietaryFactors: "Oysters, red meat, poultry, beans, and nuts.",
    lifestyleTips: [
      "Add zinc-rich foods like beans or lean meat weekly",
      "Avoid long-term high-dose zinc supplements without guidance",
    ],
  },
];

export const NUTRIENT_MAP: Record<string, NutrientDef> = Object.fromEntries(
  NUTRIENTS.map((n) => [n.key, n])
);

export type LabStatus = "low" | "normal" | "high";

export function getStatus(nutrient: NutrientDef, value: number): LabStatus {
  if (value < nutrient.low) return "low";
  if (value > nutrient.high) return "high";
  return "normal";
}

export function statusBadgeClasses(status: LabStatus): string {
  if (status === "low") return "bg-red-100 dark:bg-red-950/50 text-red-700 dark:text-red-400";
  if (status === "high") return "bg-orange-100 dark:bg-orange-950/50 text-orange-700 dark:text-orange-400";
  return "bg-emerald-100 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-400";
}

export function getStatusColor(status: LabStatus): string {
  if (status === "low") return "#ef4444"; // red
  if (status === "high") return "#f97316"; // orange
  return "#22c55e"; // green
}
